# Generated by Django 6.0.3 on 2026-03-27 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_rename_is_admin_user_is_buyer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_location', models.CharField(max_length=255)),
                ('origin_storage', models.CharField(blank=True, max_length=255)),
                ('quantity', models.IntegerField(help_text='Кількість одиниць товару')),
                ('weight', models.FloatField(help_text='Вага в кг на одиницю товару')),
                ('volume', models.FloatField(help_text="Об'єм в м3 на одиницю товару")),
                ('is_perishable', models.BooleanField(default=False, verbose_name='Швидкопсувний')),
                ('is_fragile', models.BooleanField(default=False, verbose_name='Крихкий')),
                ('is_animal_origin', models.BooleanField(default=False, verbose_name='Тваринного походження')),
                ('is_hazardous', models.BooleanField(default=False, verbose_name='Небезпечний (ADR)')),
                ('temperature_regime', models.CharField(choices=[('deep_frozen', 'Глибока заморозка (-25°C до -18°C)'), ('frozen', 'Заморозка (-18°C до -10°C)'), ('cold_chain', 'Холодний ланцюг (+2°C до +8°C)'), ('chilled', 'Охолоджене (+8°C до +15°C)'), ('ambient', 'Кімнатна температура (+15°C до +25°C)'), ('heated', 'З підігрівом (вище +25°C)'), ('no_control', 'Без контролю температури')], default='ambient', max_length=20)),
                ('manufactured_date', models.DateField(blank=True, null=True, verbose_name='Дата виробництва')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Дата закінчення терміну придатності')),
                ('notes', models.TextField(blank=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.user')),
            ],
        ),
    ]
