# Generated by Django 6.0.3 on 2026-03-27 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('origin_location', models.CharField(max_length=255)),
                ('origin_storage', models.CharField(blank=True, max_length=255)),
                ('quantity', models.IntegerField()),
                ('weight', models.FloatField(help_text='Вага однієї одиниці')),
                ('volume', models.FloatField(help_text="Об'єм однієї одиниці")),
                ('is_perishable', models.BooleanField(default=False)),
                ('is_fragile', models.BooleanField(default=False)),
                ('is_animal_origin', models.BooleanField(default=False)),
                ('is_hazardous', models.BooleanField(default=False)),
                ('temperature_regime', models.CharField(max_length=20)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.user')),
            ],
        ),
    ]
