# Generated by Django 6.0.3 on 2026-03-29 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('bakery', 'Хлібобулочні та кондитерські вироби'), ('dairy', 'Молочні продукти та яйця'), ('meat_fish', 'М’ясо, птиця та риба'), ('fruits_veg', 'Овочі та фрукти'), ('grocery', 'Бакалія та консерви'), ('beverages', 'Напої (безалкогольні та алкогольні)'), ('household', 'Побутова хімія та товари для дому'), ('hygiene', 'Гігієна та косметика'), ('electronics', 'Електроніка та техніка'), ('apparel', 'Одяг та взуття'), ('pet_supplies', 'Товари для тварин'), ('other', 'Інше / Різне')], default='other', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('origin_location', models.CharField(max_length=255)),
                ('origin_storage', models.CharField(blank=True, max_length=255)),
                ('quantity', models.IntegerField()),
                ('stock', models.CharField(choices=[('in_stock', 'В наявності'), ('out_of_stock', 'Немає в наявності'), ('pre_order', 'Під замовлення')], default='in_stock', max_length=20)),
                ('weight', models.FloatField(help_text='Вага однієї одиниці')),
                ('volume', models.FloatField(help_text="Об'єм однієї одиниці")),
                ('is_perishable', models.BooleanField(default=False)),
                ('is_fragile', models.BooleanField(default=False)),
                ('is_animal_origin', models.BooleanField(default=False)),
                ('is_hazardous', models.BooleanField(default=False)),
                ('temperature_regime', models.CharField(choices=[('deep_frozen', 'Глибока заморозка (-25°C до -18°C)'), ('frozen', 'Заморозка (-18°C до -10°C)'), ('cold_chain', 'Холодний ланцюг (+2°C до +8°C)'), ('chilled', 'Охолоджене (+8°C до +15°C)'), ('ambient', 'Кімнатна температура (+15°C до +25°C)'), ('heated', 'З підігрівом (вище +25°C)'), ('no_control', 'Без контролю температури')], default='no_control', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.user')),
            ],
        ),
    ]
