# Generated by Django 6.0.3 on 2026-03-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='in_stock', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.CharField(choices=[('in_stock', 'В наявності'), ('out_of_stock', 'Немає в наявності'), ('pre_order', 'Під замовлення')], default='in_stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='temperature_regime',
            field=models.CharField(choices=[('deep_frozen', 'Глибока заморозка (-25°C до -18°C)'), ('frozen', 'Заморозка (-18°C до -10°C)'), ('cold_chain', 'Холодний ланцюг (+2°C до +8°C)'), ('chilled', 'Охолоджене (+8°C до +15°C)'), ('ambient', 'Кімнатна температура (+15°C до +25°C)'), ('heated', 'З підігрівом (вище +25°C)'), ('no_control', 'Без контролю температури')], default='no_control', max_length=20),
        ),
    ]
