# Generated by Django 6.0.3 on 2026-03-29 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0001_initial'),
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.CharField(max_length=255)),
                ('delivery_address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('created', 'Створено'), ('confirmed', 'Підтверджено'), ('assigned', 'Призначено в доставку'), ('picked_up', 'Забрано'), ('in_transit', 'В дорозі'), ('delivered', 'Доставлено'), ('cancelled', 'Скасовано')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_started', models.DateTimeField(blank=True, null=True)),
                ('time_finished', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_as_buyer', to='users.user')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='deliveries.delivery')),
                ('products', models.ManyToManyField(related_name='orders', to='products.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_seller', to='users.user')),
            ],
        ),
    ]
