# Generated by Django 6.0.3 on 2026-03-27 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_rename_is_admin_user_is_buyer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(help_text='Вага в кг')),
                ('volume', models.FloatField(help_text="Об'єм в м3")),
                ('is_perishable', models.BooleanField(default=False, verbose_name='Швидкопсувний')),
                ('is_fragile', models.BooleanField(default=False, verbose_name='Крихкий')),
                ('is_animal_origin', models.BooleanField(default=False, verbose_name='Тваринного походження')),
                ('is_hazardous', models.BooleanField(default=False, verbose_name='Небезпечний (ADR)')),
                ('temperature_regime', models.CharField(choices=[('deep_frozen', 'Глибока заморозка (-25°C до -18°C)'), ('frozen', 'Заморозка (-18°C до -10°C)'), ('cold_chain', 'Холодний ланцюг (+2°C до +8°C)'), ('chilled', 'Охолоджене (+8°C до +15°C)'), ('ambient', 'Кімнатна температура (+15°C до +25°C)'), ('heated', 'З підігрівом (вище +25°C)'), ('no_control', 'Без контролю температури')], default='ambient', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('in_progress', 'В дорозі'), ('delivered', 'Доставлено'), ('cancelled', 'Скасовано')], default='pending', max_length=20)),
                ('gps_location', models.CharField(blank=True, max_length=255)),
                ('time_started', models.DateTimeField(blank=True, null=True)),
                ('time_finished', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_as_buyer', to='users.user')),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_as_carrier', to='users.user')),
                ('sellers', models.ManyToManyField(blank=True, related_name='orders_as_seller', to='users.user')),
            ],
        ),
    ]
