# Generated by Django 6.0.3 on 2026-03-26 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_buyer',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_employee',
            new_name='is_carrier',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_manager',
            new_name='is_seller',
        ),
    ]
