# Generated by Django 6.0.3 on 2026-03-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_buyer',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_employee',
            new_name='is_carrier',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_manager',
            new_name='is_seller',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Eridana', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(default='Hrechko', max_length=255),
            preserve_default=False,
        ),
    ]
