# Generated by Django 6.0.3 on 2026-03-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_is_admin_user_is_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Eridana', max_length=255),
            preserve_default=False,
        ),
    ]
